{
 "title": "GemFire Member Level Metrics",
 "description": "Dashboard for Tanzu GemFire with Prometheus Meter Registry",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "service_instance",
    "label": "Service Instance",
    "query": {
     "query": "label_values(geode_cache_entries{$service_instance=\"$service_instance\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Event Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"gatewaySender.*_EventQueueSize\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Member Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{cluster=\"$cluster_id\",member=\"$member\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{member=\"$member\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{member=\"$member\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{member=\"$member\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{member=\"$member\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Regions Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All entries by region",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "geode_cache_entries{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "{{region_name}} ({{data_policy}})"
      },
      {
       "expr": "sum(geode_cache_entries{cluster=\"$cluster_id\",member=\"$member\"})",
       "legendFormat": "Total Member Entries"
      }
     ]
    },
    {
     "title": "Regions",
     "type": "stat",
     "description": "# of Regions on the specified cluster and server",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(geode_cache_entries{cluster=\"$cluster_id\",member=\"$member\", region=~\".*\"})",
       "legendFormat": "# of Regions"
      }
     ]
    },
    {
     "title": "Persistent Regions",
     "type": "stat",
     "description": "% of Regions on the specified cluster and server with persistence",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(member_region_entries{cluster=\"$cluster_id\",member=\"$member\", data_policy=~\".*PERSISTENT.*\"})",
       "legendFormat": "Regions with Data persistent"
      }
     ]
    }
   ]
  },
  {
   "title": "Functions Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Successful Function Executions ",
     "type": "graph",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "geode_function_executions_seconds_count{function=~\".*internal.*\",succeeded=\"true\",member=\"$member\",cluster=\"$cluster_id\"}",
       "legendFormat": "(internal) {{function}} "
      },
      {
       "expr": "geode_function_executions_seconds_count{member=\"$member\",cluster=\"$cluster_id\",function!~\".*internal.*\",succeeded=\"true\"}",
       "legendFormat": "(user){{function}}"
      }
     ]
    },
    {
     "title": "Function Execution breakdown",
     "type": "table-old",
     "description": "Table of different function executions for the selected member and cluster.",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 14 },
     "targets": [
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\"})",
       "legendFormat": "All functions"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function=~\".*internal.*\"})",
       "legendFormat": "System functions"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function!~\".*internal.*\"})",
       "legendFormat": "User functions"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function!~\".*internal.*\",succeeded=\"true\"})",
       "legendFormat": "User functions (successful)"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function!~\".*internal.*\",succeeded=\"false\"})",
       "legendFormat": "User functions (failed)"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function=~\".*internal.*\",succeeded=\"true\"})",
       "legendFormat": "System functions (successful)"
      },
      {
       "expr": "sum(geode_function_executions_seconds_count{cluster=\"$cluster_id\",member=\"$member\",function=~\".*internal.*\",succeeded=\"false\"})",
       "legendFormat": "System functions (failed)"
      }
     ]
    },
    {
     "title": "Successful Function Execution Latency",
     "type": "graph",
     "description": "Latency measurement for successful function executions by function, for selected member and cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(geode_function_executions_seconds_sum{succeeded=\"true\",cluster=\"$cluster_id\",member=\"$member\"}[10s])/rate(geode_function_executions_seconds_count{succeeded=\"true\",cluster=\"$cluster_id\",member=\"$member\"}[10s])",
       "legendFormat": "{{$member}}.{{function}} "
      }
     ]
    },
    {
     "title": "Successful Function Execution Throughput",
     "type": "graph",
     "description": "Latency measurement for successful function executions by function, for selected member and cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(geode_function_executions_seconds_count{succeeded=\"true\",cluster=\"$cluster_id\",member=\"$member\"}[10s])",
       "legendFormat": "{{$member}}.{{function}} "
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{member=\"$member\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{member=\"$member\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{member=\"$member\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{member=\"$member\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{member=\"$member\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{member=\"$member\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster_id\",member=\"$member\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{cluster=\"$cluster_id\",member=\"$member\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{cluster=\"$cluster_id\",member=\"$member\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{cluster=\"$cluster_id\",member=\"$member\"} + process_memory_swap_bytes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{cluster=\"$cluster_id\",member=\"$member\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{cluster=\"$cluster_id\",member=\"$member\"} or jvm_threads_live_threads{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{cluster=\"$cluster_id\",member=\"$member\"} or jvm_threads_daemon_threads{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{cluster=\"$cluster_id\",member=\"$member\"} or jvm_threads_peak_threads{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{cluster=\"$cluster_id\",member=\"$member\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open{cluster=\"$cluster_id\",member=\"$member\"} or process_files_open_files{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max{cluster=\"$cluster_id\",member=\"$member\"} or process_files_max_files{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{member=\"$member\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{member=\"$member\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{member=\"$member\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{member=\"$member\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{member=\"$member\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{member=\"$member\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{cluster=\"$cluster_id\",member=\"$member\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{cluster=\"$cluster_id\",member=\"$member\"}[1m])/rate(jvm_gc_pause_seconds_count{cluster=\"$cluster_id\",member=\"$member\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{cluster=\"$cluster_id\",member=\"$member\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{cluster=\"$cluster_id\",member=\"$member\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{cluster=\"$cluster_id\",member=\"$member\"} or jvm_classes_loaded_classes{cluster=\"$cluster_id\",member=\"$member\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{application=\"$application\",instance=\"$instance\"}[5m]) or delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[5m])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{member=\"$member\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{member=\"$member\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{member=\"$member\", id=\"direct\"} or jvm_buffer_count_buffers{member=\"$member\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{member=\"$member\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{member=\"$member\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{member_name=\"$member\", id=\"mapped\"} or jvm_buffer_count_buffers{member_name=\"$member\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}